/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Test8CreateInput } from "./Test8CreateInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class CreateTest8Args {
  @ApiProperty({
    required: true,
    type: () => Test8CreateInput,
  })
  @ValidateNested()
  @Type(() => Test8CreateInput)
  @Field(() => Test8CreateInput, { nullable: false })
  data!: Test8CreateInput;
}

export { CreateTest8Args as CreateTest8Args };
