/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Test8WhereInput } from "./Test8WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Test8OrderByInput } from "./Test8OrderByInput";

@ArgsType()
class Test8FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Test8WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Test8WhereInput, { nullable: true })
  @Type(() => Test8WhereInput)
  where?: Test8WhereInput;

  @ApiProperty({
    required: false,
    type: [Test8OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Test8OrderByInput], { nullable: true })
  @Type(() => Test8OrderByInput)
  orderBy?: Array<Test8OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Test8FindManyArgs as Test8FindManyArgs };
