/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Test8WhereInput } from "./Test8WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Test8CountArgs {
  @ApiProperty({
    required: false,
    type: () => Test8WhereInput,
  })
  @Field(() => Test8WhereInput, { nullable: true })
  @Type(() => Test8WhereInput)
  where?: Test8WhereInput;
}

export { Test8CountArgs as Test8CountArgs };
